version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    target-branch: 'dev'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    target-branch: 'dev'
